const keywords = [
  "web development",
  "portfolio",
  "hemant sharma",
  "software engineer",
  "full stack developer",
  "react",
  "next.js",
  "tailwindcss",
  "typescript",
  "node.js",
  "express.js",
  "mongodb",
  "postgresql",
  "docker",
  "aws",
  "gcp",
  "azure",
  "firebase",
  "web development",
  "web design",
  "web developer",
  "web designer",
  "web developer portfolio",
  "web designer portfolio",
  "web developer resume",
  "web designer resume",
  "web developer website",
  "web designer website",
  "web developer blog",
  "web designer blog",
  "web developer projects",
  "web designer projects",
  "web developer contact",
  "web designer contact",
  "web developer about",
  "web designer about",
  "web developer services",
  "web designer services",
  "web developer skills",
  "web designer skills",
  "web developer experience",
  "web designer experience",
  "web developer education",
  "web designer education",
  "web developer certifications",
  "web designer certifications",
  "web developer awards",
  "web designer awards",
  "web developer testimonials",
  "web designer testimonials",
  "web developer clients",
  "web designer clients",
  "web developer pricing",
  "web designer pricing",
  "web developer faq",
  "web designer faq",
  "web developer blog",
  "web designer blog",
  "web developer blog posts",
  "web designer blog posts",
  "web developer blog categories",
  "web designer blog categories",
  "web developer blog tags",
  "web designer blog tags",
  "web developer blog search",
  "web designer blog search",
  "web developer blog post",
  "web designer blog post",
  "web developer blog author",
  "web designer blog author",
  "web developer blog comments",
  "web designer blog comments",
  "web developer blog newsletter",
  "web designer blog newsletter",
  "web developer blog subscribe",
  "web designer blog subscribe",
  "web developer blog share",
  "web designer blog share",
  "web developer blog related posts",
  "web designer blog related posts",
  "web developer blog popular posts",
  "web designer blog popular posts",
  "web developer blog recent posts",

  "web developer blog archive",

  "web developer blog categories",

  "web developer blog tags",

  "web developer blog search",

  "web developer blog post",

  "web developer blog author",

  "web developer blog comments",

  "web developer blog newsletter",

  "web developer blog subscribe",

  "web developer blog share",

  "web developer blog related posts",

  "web developer",
  "web developer portfolio",
];

export default keywords;
